// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha2

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CellSelector) DeepCopyInto(out *CellSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MatchExpressions != nil {
		in, out := &in.MatchExpressions, &out.MatchExpressions
		*out = make([]ResourceSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CellSelector.
func (in *CellSelector) DeepCopy() *CellSelector {
	if in == nil {
		return nil
	}
	out := new(CellSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Lockserver) DeepCopyInto(out *Lockserver) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Lockserver.
func (in *Lockserver) DeepCopy() *Lockserver {
	if in == nil {
		return nil
	}
	out := new(Lockserver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSelector) DeepCopyInto(out *ResourceSelector) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSelector.
func (in *ResourceSelector) DeepCopy() *ResourceSelector {
	if in == nil {
		return nil
	}
	out := new(ResourceSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VTComponent) DeepCopyInto(out *VTComponent) {
	*out = *in
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]v1.Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VTComponent.
func (in *VTComponent) DeepCopy() *VTComponent {
	if in == nil {
		return nil
	}
	out := new(VTComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VTCtld) DeepCopyInto(out *VTCtld) {
	*out = *in
	in.VTComponent.DeepCopyInto(&out.VTComponent)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VTCtld.
func (in *VTCtld) DeepCopy() *VTCtld {
	if in == nil {
		return nil
	}
	out := new(VTCtld)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VTGate) DeepCopyInto(out *VTGate) {
	*out = *in
	in.VTComponent.DeepCopyInto(&out.VTComponent)
	in.Credentials.DeepCopyInto(&out.Credentials)
	if in.Cells != nil {
		in, out := &in.Cells, &out.Cells
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.CellSelector.DeepCopyInto(&out.CellSelector)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VTGate.
func (in *VTGate) DeepCopy() *VTGate {
	if in == nil {
		return nil
	}
	out := new(VTGate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VTGateCredentials) DeepCopyInto(out *VTGateCredentials) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.SecretReference)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VTGateCredentials.
func (in *VTGateCredentials) DeepCopy() *VTGateCredentials {
	if in == nil {
		return nil
	}
	out := new(VTGateCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VTWorker) DeepCopyInto(out *VTWorker) {
	*out = *in
	in.VTComponent.DeepCopyInto(&out.VTComponent)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VTWorker.
func (in *VTWorker) DeepCopy() *VTWorker {
	if in == nil {
		return nil
	}
	out := new(VTWorker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessCell) DeepCopyInto(out *VitessCell) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessCell.
func (in *VitessCell) DeepCopy() *VitessCell {
	if in == nil {
		return nil
	}
	out := new(VitessCell)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitessCell) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessCellList) DeepCopyInto(out *VitessCellList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VitessCell, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessCellList.
func (in *VitessCellList) DeepCopy() *VitessCellList {
	if in == nil {
		return nil
	}
	out := new(VitessCellList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitessCellList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessCellSpec) DeepCopyInto(out *VitessCellSpec) {
	*out = *in
	out.Lockserver = in.Lockserver
	if in.VTGate != nil {
		in, out := &in.VTGate, &out.VTGate
		*out = make([]VTGate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VTWorker != nil {
		in, out := &in.VTWorker, &out.VTWorker
		*out = make([]VTWorker, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VTCtld != nil {
		in, out := &in.VTCtld, &out.VTCtld
		*out = make([]VTCtld, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessCellSpec.
func (in *VitessCellSpec) DeepCopy() *VitessCellSpec {
	if in == nil {
		return nil
	}
	out := new(VitessCellSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessCellStatus) DeepCopyInto(out *VitessCellStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessCellStatus.
func (in *VitessCellStatus) DeepCopy() *VitessCellStatus {
	if in == nil {
		return nil
	}
	out := new(VitessCellStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessCluster) DeepCopyInto(out *VitessCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessCluster.
func (in *VitessCluster) DeepCopy() *VitessCluster {
	if in == nil {
		return nil
	}
	out := new(VitessCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitessCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessClusterList) DeepCopyInto(out *VitessClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VitessCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessClusterList.
func (in *VitessClusterList) DeepCopy() *VitessClusterList {
	if in == nil {
		return nil
	}
	out := new(VitessClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitessClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessClusterSpec) DeepCopyInto(out *VitessClusterSpec) {
	*out = *in
	out.Lockserver = in.Lockserver
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessClusterSpec.
func (in *VitessClusterSpec) DeepCopy() *VitessClusterSpec {
	if in == nil {
		return nil
	}
	out := new(VitessClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessClusterStatus) DeepCopyInto(out *VitessClusterStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessClusterStatus.
func (in *VitessClusterStatus) DeepCopy() *VitessClusterStatus {
	if in == nil {
		return nil
	}
	out := new(VitessClusterStatus)
	in.DeepCopyInto(out)
	return out
}
