// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha2

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CellSelector) DeepCopyInto(out *CellSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MatchExpressions != nil {
		in, out := &in.MatchExpressions, &out.MatchExpressions
		*out = make([]ResourceSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CellSelector.
func (in *CellSelector) DeepCopy() *CellSelector {
	if in == nil {
		return nil
	}
	out := new(CellSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Etcd3Lockserver) DeepCopyInto(out *Etcd3Lockserver) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Etcd3Lockserver.
func (in *Etcd3Lockserver) DeepCopy() *Etcd3Lockserver {
	if in == nil {
		return nil
	}
	out := new(Etcd3Lockserver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyRange) DeepCopyInto(out *KeyRange) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyRange.
func (in *KeyRange) DeepCopy() *KeyRange {
	if in == nil {
		return nil
	}
	out := new(KeyRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Lockserver) DeepCopyInto(out *Lockserver) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Lockserver.
func (in *Lockserver) DeepCopy() *Lockserver {
	if in == nil {
		return nil
	}
	out := new(Lockserver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSelector) DeepCopyInto(out *ResourceSelector) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSelector.
func (in *ResourceSelector) DeepCopy() *ResourceSelector {
	if in == nil {
		return nil
	}
	out := new(ResourceSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TabletContainers) DeepCopyInto(out *TabletContainers) {
	*out = *in
	in.VTTablet.DeepCopyInto(&out.VTTablet)
	in.MySQL.DeepCopyInto(&out.MySQL)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TabletContainers.
func (in *TabletContainers) DeepCopy() *TabletContainers {
	if in == nil {
		return nil
	}
	out := new(TabletContainers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TabletCredentials) DeepCopyInto(out *TabletCredentials) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.SecretReference)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TabletCredentials.
func (in *TabletCredentials) DeepCopy() *TabletCredentials {
	if in == nil {
		return nil
	}
	out := new(TabletCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TabletDatastore) DeepCopyInto(out *TabletDatastore) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TabletDatastore.
func (in *TabletDatastore) DeepCopy() *TabletDatastore {
	if in == nil {
		return nil
	}
	out := new(TabletDatastore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VTComponent) DeepCopyInto(out *VTComponent) {
	*out = *in
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]v1.Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VTComponent.
func (in *VTComponent) DeepCopy() *VTComponent {
	if in == nil {
		return nil
	}
	out := new(VTComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VTContainer) DeepCopyInto(out *VTContainer) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VTContainer.
func (in *VTContainer) DeepCopy() *VTContainer {
	if in == nil {
		return nil
	}
	out := new(VTContainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VTCtld) DeepCopyInto(out *VTCtld) {
	*out = *in
	in.VTComponent.DeepCopyInto(&out.VTComponent)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VTCtld.
func (in *VTCtld) DeepCopy() *VTCtld {
	if in == nil {
		return nil
	}
	out := new(VTCtld)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VTGate) DeepCopyInto(out *VTGate) {
	*out = *in
	in.VTComponent.DeepCopyInto(&out.VTComponent)
	in.Credentials.DeepCopyInto(&out.Credentials)
	if in.Cells != nil {
		in, out := &in.Cells, &out.Cells
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CellSelector != nil {
		in, out := &in.CellSelector, &out.CellSelector
		*out = new(CellSelector)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VTGate.
func (in *VTGate) DeepCopy() *VTGate {
	if in == nil {
		return nil
	}
	out := new(VTGate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VTGateCredentials) DeepCopyInto(out *VTGateCredentials) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.SecretReference)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VTGateCredentials.
func (in *VTGateCredentials) DeepCopy() *VTGateCredentials {
	if in == nil {
		return nil
	}
	out := new(VTGateCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VTWorker) DeepCopyInto(out *VTWorker) {
	*out = *in
	in.VTComponent.DeepCopyInto(&out.VTComponent)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VTWorker.
func (in *VTWorker) DeepCopy() *VTWorker {
	if in == nil {
		return nil
	}
	out := new(VTWorker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessBatchOptions) DeepCopyInto(out *VitessBatchOptions) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessBatchOptions.
func (in *VitessBatchOptions) DeepCopy() *VitessBatchOptions {
	if in == nil {
		return nil
	}
	out := new(VitessBatchOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessCell) DeepCopyInto(out *VitessCell) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessCell.
func (in *VitessCell) DeepCopy() *VitessCell {
	if in == nil {
		return nil
	}
	out := new(VitessCell)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitessCell) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessCellList) DeepCopyInto(out *VitessCellList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VitessCell, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessCellList.
func (in *VitessCellList) DeepCopy() *VitessCellList {
	if in == nil {
		return nil
	}
	out := new(VitessCellList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitessCellList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessCellSpec) DeepCopyInto(out *VitessCellSpec) {
	*out = *in
	in.Lockserver.DeepCopyInto(&out.Lockserver)
	if in.VTGate != nil {
		in, out := &in.VTGate, &out.VTGate
		*out = make([]VTGate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VTWorker != nil {
		in, out := &in.VTWorker, &out.VTWorker
		*out = make([]VTWorker, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VTCtld != nil {
		in, out := &in.VTCtld, &out.VTCtld
		*out = make([]VTCtld, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessCellSpec.
func (in *VitessCellSpec) DeepCopy() *VitessCellSpec {
	if in == nil {
		return nil
	}
	out := new(VitessCellSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessCellStatus) DeepCopyInto(out *VitessCellStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessCellStatus.
func (in *VitessCellStatus) DeepCopy() *VitessCellStatus {
	if in == nil {
		return nil
	}
	out := new(VitessCellStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessCluster) DeepCopyInto(out *VitessCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessCluster.
func (in *VitessCluster) DeepCopy() *VitessCluster {
	if in == nil {
		return nil
	}
	out := new(VitessCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitessCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessClusterList) DeepCopyInto(out *VitessClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VitessCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessClusterList.
func (in *VitessClusterList) DeepCopy() *VitessClusterList {
	if in == nil {
		return nil
	}
	out := new(VitessClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitessClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessClusterSpec) DeepCopyInto(out *VitessClusterSpec) {
	*out = *in
	if in.Lockserver != nil {
		in, out := &in.Lockserver, &out.Lockserver
		*out = new(VitessLockserver)
		(*in).DeepCopyInto(*out)
	}
	if in.LockserverRef != nil {
		in, out := &in.LockserverRef, &out.LockserverRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.Cells != nil {
		in, out := &in.Cells, &out.Cells
		*out = make([]VitessCell, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CellSelector != nil {
		in, out := &in.CellSelector, &out.CellSelector
		*out = make([]ResourceSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Keyspaces != nil {
		in, out := &in.Keyspaces, &out.Keyspaces
		*out = make([]VitessKeyspace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.KeyspaceSelector != nil {
		in, out := &in.KeyspaceSelector, &out.KeyspaceSelector
		*out = make([]ResourceSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessClusterSpec.
func (in *VitessClusterSpec) DeepCopy() *VitessClusterSpec {
	if in == nil {
		return nil
	}
	out := new(VitessClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessClusterStatus) DeepCopyInto(out *VitessClusterStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessClusterStatus.
func (in *VitessClusterStatus) DeepCopy() *VitessClusterStatus {
	if in == nil {
		return nil
	}
	out := new(VitessClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessContainerOptions) DeepCopyInto(out *VitessContainerOptions) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessContainerOptions.
func (in *VitessContainerOptions) DeepCopy() *VitessContainerOptions {
	if in == nil {
		return nil
	}
	out := new(VitessContainerOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessKeyspace) DeepCopyInto(out *VitessKeyspace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessKeyspace.
func (in *VitessKeyspace) DeepCopy() *VitessKeyspace {
	if in == nil {
		return nil
	}
	out := new(VitessKeyspace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitessKeyspace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessKeyspaceList) DeepCopyInto(out *VitessKeyspaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VitessKeyspace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessKeyspaceList.
func (in *VitessKeyspaceList) DeepCopy() *VitessKeyspaceList {
	if in == nil {
		return nil
	}
	out := new(VitessKeyspaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitessKeyspaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessKeyspaceOptions) DeepCopyInto(out *VitessKeyspaceOptions) {
	*out = *in
	out.Shards = in.Shards
	out.Replicas = in.Replicas
	out.Batch = in.Batch
	out.Containers = in.Containers
	if in.Cells != nil {
		in, out := &in.Cells, &out.Cells
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CellSelector != nil {
		in, out := &in.CellSelector, &out.CellSelector
		*out = make([]ResourceSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessKeyspaceOptions.
func (in *VitessKeyspaceOptions) DeepCopy() *VitessKeyspaceOptions {
	if in == nil {
		return nil
	}
	out := new(VitessKeyspaceOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessKeyspaceSpec) DeepCopyInto(out *VitessKeyspaceSpec) {
	*out = *in
	in.Defaults.DeepCopyInto(&out.Defaults)
	if in.Shards != nil {
		in, out := &in.Shards, &out.Shards
		*out = make([]VitessShard, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ShardSelector != nil {
		in, out := &in.ShardSelector, &out.ShardSelector
		*out = make([]ResourceSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessKeyspaceSpec.
func (in *VitessKeyspaceSpec) DeepCopy() *VitessKeyspaceSpec {
	if in == nil {
		return nil
	}
	out := new(VitessKeyspaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessKeyspaceStatus) DeepCopyInto(out *VitessKeyspaceStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessKeyspaceStatus.
func (in *VitessKeyspaceStatus) DeepCopy() *VitessKeyspaceStatus {
	if in == nil {
		return nil
	}
	out := new(VitessKeyspaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessLockserver) DeepCopyInto(out *VitessLockserver) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessLockserver.
func (in *VitessLockserver) DeepCopy() *VitessLockserver {
	if in == nil {
		return nil
	}
	out := new(VitessLockserver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitessLockserver) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessLockserverList) DeepCopyInto(out *VitessLockserverList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VitessLockserver, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessLockserverList.
func (in *VitessLockserverList) DeepCopy() *VitessLockserverList {
	if in == nil {
		return nil
	}
	out := new(VitessLockserverList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitessLockserverList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessLockserverSpec) DeepCopyInto(out *VitessLockserverSpec) {
	*out = *in
	if in.Etcd3 != nil {
		in, out := &in.Etcd3, &out.Etcd3
		*out = new(Etcd3Lockserver)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessLockserverSpec.
func (in *VitessLockserverSpec) DeepCopy() *VitessLockserverSpec {
	if in == nil {
		return nil
	}
	out := new(VitessLockserverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessLockserverStatus) DeepCopyInto(out *VitessLockserverStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessLockserverStatus.
func (in *VitessLockserverStatus) DeepCopy() *VitessLockserverStatus {
	if in == nil {
		return nil
	}
	out := new(VitessLockserverStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessReplicaOptions) DeepCopyInto(out *VitessReplicaOptions) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessReplicaOptions.
func (in *VitessReplicaOptions) DeepCopy() *VitessReplicaOptions {
	if in == nil {
		return nil
	}
	out := new(VitessReplicaOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessShard) DeepCopyInto(out *VitessShard) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessShard.
func (in *VitessShard) DeepCopy() *VitessShard {
	if in == nil {
		return nil
	}
	out := new(VitessShard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitessShard) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessShardList) DeepCopyInto(out *VitessShardList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VitessShard, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessShardList.
func (in *VitessShardList) DeepCopy() *VitessShardList {
	if in == nil {
		return nil
	}
	out := new(VitessShardList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitessShardList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessShardOptions) DeepCopyInto(out *VitessShardOptions) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessShardOptions.
func (in *VitessShardOptions) DeepCopy() *VitessShardOptions {
	if in == nil {
		return nil
	}
	out := new(VitessShardOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessShardSpec) DeepCopyInto(out *VitessShardSpec) {
	*out = *in
	out.Defaults = in.Defaults
	out.KeyRange = in.KeyRange
	if in.Tablets != nil {
		in, out := &in.Tablets, &out.Tablets
		*out = make([]VitessTablet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TabletSelector != nil {
		in, out := &in.TabletSelector, &out.TabletSelector
		*out = make([]ResourceSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessShardSpec.
func (in *VitessShardSpec) DeepCopy() *VitessShardSpec {
	if in == nil {
		return nil
	}
	out := new(VitessShardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessShardStatus) DeepCopyInto(out *VitessShardStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessShardStatus.
func (in *VitessShardStatus) DeepCopy() *VitessShardStatus {
	if in == nil {
		return nil
	}
	out := new(VitessShardStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessTablet) DeepCopyInto(out *VitessTablet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessTablet.
func (in *VitessTablet) DeepCopy() *VitessTablet {
	if in == nil {
		return nil
	}
	out := new(VitessTablet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitessTablet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessTabletList) DeepCopyInto(out *VitessTabletList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VitessTablet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessTabletList.
func (in *VitessTabletList) DeepCopy() *VitessTabletList {
	if in == nil {
		return nil
	}
	out := new(VitessTabletList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VitessTabletList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessTabletSpec) DeepCopyInto(out *VitessTabletSpec) {
	*out = *in
	out.Keyrange = in.Keyrange
	out.Datastore = in.Datastore
	in.Containers.DeepCopyInto(&out.Containers)
	if in.VolumeClaim != nil {
		in, out := &in.VolumeClaim, &out.VolumeClaim
		*out = new(v1.PersistentVolumeClaimVolumeSource)
		**out = **in
	}
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(TabletCredentials)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessTabletSpec.
func (in *VitessTabletSpec) DeepCopy() *VitessTabletSpec {
	if in == nil {
		return nil
	}
	out := new(VitessTabletSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VitessTabletStatus) DeepCopyInto(out *VitessTabletStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VitessTabletStatus.
func (in *VitessTabletStatus) DeepCopy() *VitessTabletStatus {
	if in == nil {
		return nil
	}
	out := new(VitessTabletStatus)
	in.DeepCopyInto(out)
	return out
}
