## Sample VitessCluster all-in-one resource
apiVersion: vitess.io/v1alpha2
kind: VitessCluster
metadata:
  name: simple
  labels:
    app: vitess
spec:
  # lockserver is an embeded VitessLockserverSpec
  lockserver:
    etcd2:
      address: etcd-global-client:2379
      path: /vitess/global
  # cells is a map of cell names to VitessCellSpecs
  cells:
    zone1:
      lockserver:
        type: etcd2
        etcd2:
          address: etcd-zone1-client:2379
          path: /vitess/zone1
      defaults:
        replicas: 1
        image: vitess/vttablet:helm-1.0.4
  # keyspaces is a map of strings to VitessKeyspaceSpecs
  keyspaces:
    unsharded-dbname:
      shards:
        "0":
          defaults:
            replicas: 2
            containers:
              mysql:
                image: percona:5.7.23
              vttablet:
                image: vitess/vttablet:helm-1.0.4
          # tablets is a map of strings to VitessTabletSpecs
          tablets:
            zone1-101:
              tabletId: 101
              cell: zone1
              type: replica
    # messagedb:
    #   # shards is a map of strings to VitessShardSpecs
    #   shards:
    #     X-80:
    #       keyrange: { to: "80" }
    #       # tablets is a map of strings to VitessTabletSpecs
    #       tablets:
    #         uswest-101:
    #           tabletId: 101
    #           cell: uswest
    #           type: "replica"
    #           keyrange: { to: "80" }
    #     80-X:
    #       keyrange: { from: "80" }
    #       # tablets is a map of strings to VitessTabletSpecs
    #       tablets:
    #         uswest-201:
    #           tabletId: 201
    #           cell: uswest
    #           type: "replica"
    #           keyrange: { from: "80" }
# Status shown here as an example only
# status:
#   state: ""
#   # lockserver is an embeded VitessLockserverStatus object
#   lockserver:
#     state: ""
#   # cells is a map of strings to VitessCellStatus objects
#   cells:
#     uswest:
#       state: ""
#   # keyspaces is a map of strings to VitessKeyspaceStatus objects
#   keyspaces:
#     messagedb:
#       state: ""
#       # shards is a map of strings to VitessShardStatus objects
#       shards:
#         X-80:
#           state: ""
#           # tablets is a map of strings to VitessTabletStatus objects
#           tablets:
#             uswest-101:
#               state: ""
#             uswest-201:
#               state: ""
